/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipShuttleRouteImport } from './routes/vip-shuttle'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChauffeurServiceRouteImport } from './routes/chauffeur-service'
import { Route as BusinessLangzeitmieteRouteImport } from './routes/business-langzeitmiete'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FleetIndexRouteImport } from './routes/fleet.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as FleetVehicleIdRouteImport } from './routes/fleet.$vehicleId'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const VipShuttleRoute = VipShuttleRouteImport.update({
  id: '/vip-shuttle',
  path: '/vip-shuttle',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChauffeurServiceRoute = ChauffeurServiceRouteImport.update({
  id: '/chauffeur-service',
  path: '/chauffeur-service',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessLangzeitmieteRoute = BusinessLangzeitmieteRouteImport.update({
  id: '/business-langzeitmiete',
  path: '/business-langzeitmiete',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetIndexRoute = FleetIndexRouteImport.update({
  id: '/fleet/',
  path: '/fleet/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const FleetVehicleIdRoute = FleetVehicleIdRouteImport.update({
  id: '/fleet/$vehicleId',
  path: '/fleet/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/business-langzeitmiete': typeof BusinessLangzeitmieteRoute
  '/chauffeur-service': typeof ChauffeurServiceRoute
  '/contact': typeof ContactRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/vip-shuttle': typeof VipShuttleRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/fleet/$vehicleId': typeof FleetVehicleIdRoute
  '/admin/': typeof AdminIndexRoute
  '/fleet/': typeof FleetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-langzeitmiete': typeof BusinessLangzeitmieteRoute
  '/chauffeur-service': typeof ChauffeurServiceRoute
  '/contact': typeof ContactRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/vip-shuttle': typeof VipShuttleRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/fleet/$vehicleId': typeof FleetVehicleIdRoute
  '/admin': typeof AdminIndexRoute
  '/fleet': typeof FleetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/business-langzeitmiete': typeof BusinessLangzeitmieteRoute
  '/chauffeur-service': typeof ChauffeurServiceRoute
  '/contact': typeof ContactRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/vip-shuttle': typeof VipShuttleRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/fleet/$vehicleId': typeof FleetVehicleIdRoute
  '/admin/': typeof AdminIndexRoute
  '/fleet/': typeof FleetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/business-langzeitmiete'
    | '/chauffeur-service'
    | '/contact'
    | '/datenschutz'
    | '/impressum'
    | '/vip-shuttle'
    | '/admin/dashboard'
    | '/fleet/$vehicleId'
    | '/admin/'
    | '/fleet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/business-langzeitmiete'
    | '/chauffeur-service'
    | '/contact'
    | '/datenschutz'
    | '/impressum'
    | '/vip-shuttle'
    | '/admin/dashboard'
    | '/fleet/$vehicleId'
    | '/admin'
    | '/fleet'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/business-langzeitmiete'
    | '/chauffeur-service'
    | '/contact'
    | '/datenschutz'
    | '/impressum'
    | '/vip-shuttle'
    | '/admin/dashboard'
    | '/fleet/$vehicleId'
    | '/admin/'
    | '/fleet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BusinessLangzeitmieteRoute: typeof BusinessLangzeitmieteRoute
  ChauffeurServiceRoute: typeof ChauffeurServiceRoute
  ContactRoute: typeof ContactRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  VipShuttleRoute: typeof VipShuttleRoute
  FleetVehicleIdRoute: typeof FleetVehicleIdRoute
  FleetIndexRoute: typeof FleetIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip-shuttle': {
      id: '/vip-shuttle'
      path: '/vip-shuttle'
      fullPath: '/vip-shuttle'
      preLoaderRoute: typeof VipShuttleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chauffeur-service': {
      id: '/chauffeur-service'
      path: '/chauffeur-service'
      fullPath: '/chauffeur-service'
      preLoaderRoute: typeof ChauffeurServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-langzeitmiete': {
      id: '/business-langzeitmiete'
      path: '/business-langzeitmiete'
      fullPath: '/business-langzeitmiete'
      preLoaderRoute: typeof BusinessLangzeitmieteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/': {
      id: '/fleet/'
      path: '/fleet'
      fullPath: '/fleet/'
      preLoaderRoute: typeof FleetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/fleet/$vehicleId': {
      id: '/fleet/$vehicleId'
      path: '/fleet/$vehicleId'
      fullPath: '/fleet/$vehicleId'
      preLoaderRoute: typeof FleetVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BusinessLangzeitmieteRoute: BusinessLangzeitmieteRoute,
  ChauffeurServiceRoute: ChauffeurServiceRoute,
  ContactRoute: ContactRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  VipShuttleRoute: VipShuttleRoute,
  FleetVehicleIdRoute: FleetVehicleIdRoute,
  FleetIndexRoute: FleetIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
